### ISSUE TITLE
Cosmos DB general functionality

### ISSUE THREAD

**Issue by dArignac** [supplyon/gremcos#1]
Ensure that the lib can work with Azure CosmosDB.

- general queries are possible
- re-connection handling
- provide data for a health endpoint
- proper tests with coverage

**Comment by ThomasObenaus** [comment]
# For review:
* proper tests with coverage: #3  #6 
* re-connection handling: #9 
* provide data for a health endpoint: #7 
* general queries are possible: [gremlin example](https://github.com/supplyon/go-gremlin-cosmos/blob/master/examples/local/main.go)
