### ISSUE TITLE
Authentication with cosmos db

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#31]
A quick question regarding auth.
I would like to see some information on the Auth options in readme. For instance, can we use SPN token via AAD to authenticate the cosmos client?

**Comment by dArignac** [comment]
Hi @kwontae,

Azure Cosmos DB is not tied to the AAD for authenticating clients (as far as I know). There are basically only 2 ways to authenticate, either with the master key or with resource tokens. See here for more details: https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data
