### ISSUE TITLE
g.V(<Vertex name> string)

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#38]
I went through the graph interface, but couldn't find one for `g.V("id1")` as I don't want to make a query using `g.V()` due to the efficiency issue. 
Is it possible to add a functionality where I can query for a specific vertex using the id name?

**Comment by kwontae** [comment]
```
func (g *graph) VByStr(id string) interfaces.Vertex {
    vertex := NewVertexG(g)
    vertex.Add(NewSimpleQB(".V(\"%s\")", id))
    return vertex
}
```
something like this

**Comment by ThomasObenaus** [comment]
@kwontae we added the demanded function. happy coding :-)

**Comment by kwontae** [comment]
@ThomasObenaus @dArignac  When will you guys be releasing this code merge so I don't have to use a custom repo with `.VByStr`?

**Comment by ThomasObenaus** [comment]
@kwontae its not planned in the next 2-3 weeks to release a new tag. But with go mod you can always refer to the current revision on the master.

if you call `go get github.com/supplyon/gremcos@master` you will pull in the current revision into your go.mod file getting this newest change.

**Comment by kwontae** [comment]
@ThomasObenaus  ohhh that's good to know! Thank you!
