### ISSUE TITLE
responses.ToProperties() returning error due to invalid key

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#40]
When I run a query of `g.VByStr("ExampleID")`
I can run `responses.ToValues()` and iterate through the values
However, when I run `responses.ToProperties()`, I get this error message

`* '' has invalid keys: properties, type`

**Comment by dArignac** [comment]
Hi @kwontae, we'll have a look into it.

**Comment by kwontae** [comment]
@dArignac  thank you!

**Comment by ThomasObenaus** [comment]
@kwontae sorry for not come back so far (had no time yet). 
But we will look into it and give feedback until end of the week.

**Comment by dressedfez** [comment]
I have found this: https://stackoverflow.com/a/47175617/2823940. Are those properties maybe not comparable and they are used in a map?

**Comment by ThomasObenaus** [comment]
Hey @kwontae,

can you give me pls some more information? 

How does the vertex ("ExampleID") actually look like? To analyse the issue I need to understand the structure of the vertex that you have in your example.
Is it possible to post a screenshot of the vertex its values and properties from the azure ui?
If not, pls have a look at [infra](https://github.com/supplyon/gremcos/tree/master/infra). There is described how you can connect against a azure cosmos graph db. There you can query for that node "ExampleID". And then please provide the output.

**Comment by kwontae** [comment]
@ThomasObenaus  So you want the screenshot from the UI instead of the JSON?

**Comment by kwontae** [comment]
![image](https://user-images.githubusercontent.com/24832412/91896634-0abd3e00-ec4e-11ea-87cc-b6e2bf8748d2.png)

**Comment by kwontae** [comment]
```
[
  {
    "id": "example",
    "label": "device",
    "type": "vertex",
    "properties": {
      "pk": [
        {
          "id": "example",
          "value": "example"
        }
      ],
      "deviceIPAddress": [
        {
          "id": "example",
          "value": ".36"
        }
      ],
      "critical": [
        {
          "id": "example",
          "value": "No"
        }
      ],
      "placeInNetwork": [
        {
          "id": "example-f57f0a21dfde",
          "value": "example_bldg-example"
        }
      ],
      "vendor": [
        {
          "id": "example-example-example-example-eb02386bacd3",
          "value": "example"
        }
      ],
      "deviceModel": [
        {
          "id": "example-example-example-b150-976553721ca4",
          "value": "example 10506e"
        }
      ],
      "deviceTypeName": [
        {
          "id": "example-example-example-9c7e-50bc3ab37313",
          "value": "Switch"
        }
      ],
      "region": [
        {
          "id": "example-example-4698-example-1ee85c528c66",
          "value": "A"
        }
      ],
      "snmpDomain": [
        {
          "id": "example-20a2-example-example-4eefa4e22898",
          "value": "example"
        }
      ],
      "sysObjID": [
        {
          "id": "example-example-4b5f-example-fde71caa478b",
          "value": "1.2.3.4.5.6.7"
        }
      ],
      "deviceFamily": [
        {
          "id": "example-example-example-9a91-7b8ff62e9378",
          "value": "example OS"
        }
      ],
      "userName": [
        {
          "id": "example-example-4171-example-fb8d25a49de5",
          "value": "example"
        }
      ],
      "assetTag": [
        {
          "id": "example-2958-example-example-99b18ee05fa0",
          "value": "12345678"
        }
      ],
      "createdAt": [
        {
          "id": "example-example-example-example-543efdc271fe",
          "value": "2020-08-20T04:16:08.7220998Z"
        }
      ]
    }
  }
]

**Comment by kwontae** [comment]
@ThomasObenaus any updates?

**Comment by ThomasObenaus** [comment]
@kwontae I'm on it.

**Comment by ThomasObenaus** [comment]
I will enhance the code documentation a bit to make that point more clear.
Additionally I'll try to adjust the error message a bit to point to that issue.

**Comment by kwontae** [comment]
AH interesting. So what you are saying is that **ToProperties()** isn't for extracting the property values without the `id` of every property. I understood this as extract only the properties of returned vertices. That makes more sense. May I ask what you would suggest for only getting the `k,v` pair? For example 
```
"createdAt": [
        {
          #remove "id": "example-example-example-example-543efdc271fe",
          "value": "2020-08-20T04:16:08.7220998Z"
        }
 ]
```

I was thinking of just iterating through all properties and map the key and the value myself, but i wasn't sure if gremlin had a support for removing the subdocument id...

**Comment by ThomasObenaus** [comment]
@kwontae exactly the ToXYZ() methods don't have any internal logic to determine subtypes in the given response in order to extract it and map it. Hence if you have a Vertex or Edge as an response you can't extract the properties directly with the ToProperties() method.

But to get the data you need you have the following options

h2. Option 1 (.Properties() + ToProperties())
If you adjust your query to `g.VByStr("ExampleID").Properties()` then the response by cosmos is
```
[
 ....the other props..},
  {
    "id": "example-example-example-example-543efdc271fe",
    "value": "2020-08-20T04:16:08.7220998Z",
    "label": "createdAt"
  }
]
```
Then you can iterate over the array of properites 
```
responses := api.ResponseArray(res)
props, err := responses.ToProperties()
for _,prop := range props{
   fmt.Printf("%s = %s\n",prop.label,prop.value.AsString())
}
```

h2. Option 2 (.Values() + ToValues())
If you adjust your query to `g.VByStr("ExampleID").Values()` then the response by cosmos is
```
[
  "example",
  ".36",
  "No",
  "example_bldg-example",
  "example",
  "example 10506e",
  "Switch",
  "A",
  "example",
  "1.2.3.4.5.6.7",
  "example OS",
  "example",
  "12345678",
  "2020-08-20T04:16:08.7220998Z"
]
```
Then you can iterate over the array of values 
```
responses := api.ResponseArray(res)
vals, err := responses.ToValues()
for _,value := range vals{
   fmt.Printf("%s\n",value.AsString())
}
```

h2. Option 3 (.ValueMap() + ToValueMap())

If you adjust your query to `g.VByStr("ExampleID").ValueMap()` then the response by cosmos is
```

[{
  "pk" : ["example"],
  "deviceIPAddress" : [".36"],
  "critical" : ["No"],
  "placeInNetwork" : ["example_bldg-example"],
  "vendor" : ["example"],
  "deviceModel" : ["example 10506e"],
  "deviceTypeName" : ["Switch"],
  "region" : ["A"],
  "snmpDomain" : ["example"],
  "sysObjID" : ["1.2.3.4.5.6.7"],
  "deviceFamily" : ["example OS"],
  "userName" : ["example"],
  "assetTag" : ["12345678"],
  "createdAt" : ["2020-08-20T04:16:08.7220998Z]"
}
]
```
Then you can iterate over the array of values 
```
responses := api.ResponseArray(res)
vals, err := responses.ToValueMap()
for key,value := range vals{
   fmt.Printf("%s = %s\n",key,value.AsString())
}
```

**Comment by ThomasObenaus** [comment]
If you are only interested in the `label` and the `value` then I suggest to use option 3 but option 1 is also viable. 
I hope this helps.

**Comment by kwontae** [comment]
Thank you for the suggestions! This issue can be closed now 👍
