### ISSUE TITLE
Mocking cosmos object for unit-test

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#41]
I wrote a cosmos driver (basically a wrapper around gremcos) and I want to write some unit tests for the operations that I've implemented for this wrapper "class". I saw that your library has an unexported function to set the websocket generator. Is it possible to expose that function to allow consumers of this package to write a unit test around their wrapper? I'm still relatively new to Golang so I would be interested in getting some advice on how to go about writing unit tests in a situation like this.

Thank you!

**Comment by dArignac** [comment]
Hi @kwontae,

we use [gomock](https://github.com/golang/mock) for mocking and mock the methods `Execute` and ` ExecuteQuery` of `cosmos.go` with it, to not access the graph database in the tests directly. I guess you could go this way too, and avoid mocking the WebSocket stuff directly.

Therefore we have an interface in our project that uses `gremcos`:

```
// ./interfaces/cosmos.go
package interfaces

import "github.com/supplyon/gremcos/interfaces"

type Cosmos interface {
	ExecuteQuery(query interfaces.QueryBuilder) ([]interfaces.Response, error)
	Execute(query string) ([]interfaces.Response, error)
}
```

And we create the proper mock with this call `mockgen -source=interfaces/cosmos.go -destination test/mocks/interfaces/mock_cosmos.go`. 

Within the test, we use the mock like this:

```
import (
	mock_cosmos "yourrepo.com/project/test/mocks/interfaces"
	"github.com/golang/mock/gomock"
	gremcos_if "github.com/supplyon/gremcos/interfaces"
)

func Test_Sample(t *testing.T) {
	mockCtrl := gomock.NewController(t)
	defer mockCtrl.Finish()
	mockedCosmos := mock_cosmos.NewMockCosmos(mockCtrl)
	repoIF, err := New(mockedCosmos)
	require.NoError(t, err)
	require.NotNil(t, repoIF)
	repo := repoIF.(*repository)

	mockedCosmos.EXPECT().ExecuteQuery(repo.graph.V().HasLabel("demo").Id()).Return(responses, nil)
}
```

The `repository` is a struct we use to tie together all relevant functionality and interaction with the graph database:

```
type repository struct {
	graph    gremcos_if.Graph
}
```

I hope this gives the big picture how you could mock it. Not sure if that will be helpful for what you want to do. If not, just tell us and we'll have a look into the function signatures.

**Comment by kwontae** [comment]
Thanks for the input! Closing this.
