### ISSUE TITLE
Ability to query outE({label})

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#45]
is it possible to change the `OutE()` to `OutE(labels ...string)` which would make sure the label remains optional, but if `len(label) > 0` then we use the `labels` and add `outE('hasInterface','hasSomethingElse')` to the query?

**Comment by kwontae** [comment]
how about something like this?
```
// OutE adds .outE(label(s)), to the query. The query call returns all outgoing edges of the Vertex
func (v *vertex) OutE(labels ...string) interfaces.Edge {
	labelStr := ""
	if len(labels) > 0 {
		labelStr += fmt.Sprintf("'%s'", labels[0])
		for i := 1; i < len(labels); i++) {
			labelStr += fmt.Sprintf(",'%s'", labels[i])
		}
	}
	v.Add(NewSimpleQB(".outE(%s)", labelStr))
	return NewEdgeV(v)
}
```
@dArignac

**Comment by kwontae** [comment]
Similar idea could be applied for `.HasLabel(label string)`
```
// HasLabel adds .hasLabel("<label>"), e.g. .hasLabel("user"), to the query. The query call returns all edges with the given label.
func (e *edge) HasLabel(label string, extraLabels ...string) interfaces.Edge {
	if len(extraLabels) > 0 {
		for _, l := range extraLabels {
			label += fmt.Sprintf(",'%s'", l)
		}
	}
	return e.Add(NewSimpleQB(".hasLabel(\"%s\")", label))
}
```

**Comment by kwontae** [comment]
this is a big blocker for our work

**Comment by ThomasObenaus** [comment]
@kwontae l'll have a look.

**Comment by kwontae** [comment]
@ThomasObenaus  Made tiny edits in the code snippets to fix some string matching error

**Comment by ThomasObenaus** [comment]
@kwontae With #46 the changes you are looking for are implemented. Sadly you have to wait a while until the PR is reviewed by @dArignac. This could take some time (approx 1-2 weeks) since he is not available at the moment.

However you could also already take a look and work from the branch where I pushed the changes.
You can get that branch by `go get github.com/supplyon/gremcos@2c8b6efa3578cb642f3f6ee71915b29bee3fd2f5`

**Comment by kwontae** [comment]
@ThomasObenaus Thank you for working on this request! I did a quick review of the PR myself with some knowledge i've gained while trying to find the best solution that you guys could possibly incorporate if that's okay. I will test the functionality using that branch while this PR is being reviewed!

**Comment by dArignac** [comment]
I approved it @ThomasObenaus .

**Comment by ThomasObenaus** [comment]
PR merged + issue closed
