### ISSUE TITLE
adding the `.as()` functionality

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#47]
Is it possible to add the `.as()` functionality on the edge and vertex interface? I need a way to assign variables to select both vertex and edge properties. If you have any workarounds for temporary solution, please let me know as well

**Comment by dArignac** [comment]
Hi @kwontae, sorry for responding so late. We'll have a look into this soon.

**Comment by dArignac** [comment]
Hi @kwontae, the issue is now fixed.
