### ISSUE TITLE
How to set timeout in dialer for the gremcos.Cosmos client

### ISSUE THREAD

**Issue by kwontae** [supplyon/gremcos#65]
As the customer pool is growing, we are starting to see a lot of errors where the query will return an error due to no result for respons {id}. I believe this may be due to the Timeout settings of a dialer.

We've already scaled up the # of kubernetes replica set, increased the connection idle timeout to the ideal time explained by the microsoft doc (1 hour) and increased the NumMaxActiveConnections to 100, but still seeing the same issue. The last thing I can think of is possibly setting the Http client/Dialer timeout setting that will match the connection idle timeout, but I don't see an option to be able to set it in the `gremcos.New(host string, ...Options)`

Can you assist on how I can create the same cosmos client with a timeout setting?

Sincerely,

Taehyun Kwon

**Comment by kwontae** [comment]
An update: 
we are getting an error 
`query: g.V("cusred123ca901").has("pk","cusred123ca901").outE("hasCDPNeighbor").as('e').inV().as('v').select('e','v').by(valueMap()): No result for response with id 49326a56-7015-4ed3-812b-86f99894bee8 found`

When I query this exact same query directly in cosmos db, i get the results back.

Do you have an idea of what might be happening and advice on best practices using this library?

**Comment by kwontae** [comment]
@dArignac  @ThomasObenaus  any updates?

**Comment by dArignac** [comment]
@ThomasObenaus  can you have a look?
@kwontae sorry for the delay, we try to investigate asap.

**Comment by ThomasObenaus** [comment]
@kwontae regarding your question about the time out: The only thing I can imagine is tweaking the timeouts on the websocket connection a bit (see: https://github.com/supplyon/gremcos/blob/master/connection.go#L30-L41).

But I guess this won't help to fix the issues you see.

So far I also don't see how the error you reported can occur in case the data you are actually querying for is present.

Could you please give some hints (maybe code example) how to reproduce the issue?
Besides of that could you probably provide some logs (only the gremcos part)?

The more information we can get the easier it is to find the root cause.

**Comment by ThomasObenaus** [comment]
@kwontae with https://github.com/supplyon/gremcos/pull/68 I added a bit more details on the "No result for response with id..." error you get. Can you please try to reproduce the issue using the latest version (v0.1.8) and post the full error message here?
This version includes as well the `as()` step as part of the query api.

**Comment by ThomasObenaus** [comment]
@kwontae with https://github.com/supplyon/gremcos/pull/68 I added a bit more details on the "No result for response with id..." error you get. Can you please try to reproduce the issue using the latest version (v0.1.8) and post the full error message here?

**Comment by kwontae** [comment]
@ThomasObenaus  sorry about the delay, due to the time, we have moved on to some other features with workarounds by using a different framework as of now, but we would really like to go back to using Go. I will tackle this again starting next Sprint (next week) if that's okay with you.

**Comment by dArignac** [comment]
@kwontae No problem.

**Comment by ThomasObenaus** [comment]
@kwontae did you found some time to try to reproduce the issue?

**Comment by kwontae** [comment]
Hey @ThomasObenaus, sorry about this. I've been reassigned to work on a higher priority feature and bunch of other personal events so I didn't get a chance... I will go ahead and upgrade our package, revive the go application and let it run for some time!
