### ISSUE TITLE
SonarCloud not supported for PRs from forks

### ISSUE THREAD

**Issue by ThomasObenaus** [supplyon/gremcos#78]
## Problem
When a PR is created from a fork no secrets are passed by the github runner to the external runner.
See here 
![image](https://user-images.githubusercontent.com/1695514/134067028-751141b8-307a-4473-85ce-4d9c750bbb54.png)
and [here](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

But since sonar cloud scan needs the SONAR_TOKEN to be set. It is not possible to have a successful pipeline run in case the PR was provided via fork.

Related Issue at SonarCloud: https://jira.sonarsource.com/browse/MMF-1371

**Comment by ThomasObenaus** [comment]
Disabled SonarCloud for now completely.

Maybe it is somehow possible to exclude it only for PRs from forks.

**Comment by ThomasObenaus** [comment]
Found a way to disable sonar cloud scan for external PRs (from forks) only.

**Comment by dArignac** [comment]
We can alternatively use CodeQL or similar.
